### ISSUE TITLE
Documentation feedback: Broken link

### ISSUE THREAD

**Issue by rustyjux** [bcgov/bcdg#15]
#### The highlighted text: 

 > Confirm your authority to license

 #### The comment on the text: 
Link is broken - missing path `use-github-in-bcgov/license-your-github-repository/`

 ___
B.C. government DevHub URL: <https://mvp.developer.gov.bc.ca/docs/default/component/bc-developer-guide/use-github-in-bcgov/start-working-in-bcgov-github-organization/> 
Markdown URL: <https://github.com/bcgov/bcdg/blob/main/docs/use-github-in-bcgov/start-working-in-bcgov-github-organization.md>

**Comment by jenreiher-bcgov** [comment]
Thanks for your feedback! This has been addressed. In future, you are super welcome to make a PR to fix small bugs like this to help it get addressed faster :)
