### ISSUE TITLE
Missing PHP

### ISSUE THREAD

**Issue by kmarshgov** [bcgov/bcdg#46]
https://github.com/bcgov/bcdg/blob/1ca6afc63802f5a292bedffca43c62012b096a16/docs/choosing-technology/how-to-select-technology.md?plain=1#L13

and missing Laravel as a backend framework.

**Comment by jenreiher-bcgov** [comment]
Hi @kmarshgov thanks for your feedback, good call. We are open to PRs on this documentation - would you interested in contributing?

**Comment by kmarshgov** [comment]
@jenreiher-bcgov I tried to do a PR but not sure why it failed the checks. Regardless, the changes I'm suggesting are minor if you'd like to add them.

**Comment by jenreiher-bcgov** [comment]
@kmarshgov this is expected - we have something in our backlog to improve, but haven't gotten there yet. I'll review - thank you so much for your contribution! We appreciate it.

**Comment by MonicaG** [comment]
Closing as this was merged in #47
Feel free to reopen if this was not the case
