### ISSUE TITLE
Documentation feedback: There are a few setup steps, which we'll cover below) but after that, ...

### ISSUE THREAD

**Issue by MaxWardle** [bcgov/bcdg#9]
## Documentation Feedback 📝

In [this section](https://mvp.developer.gov.bc.ca/docs/default/component/bc-developer-guide/content-partner-guide/#how-does-documentation-work-in-devhub) at the end of the first paragraph there's a closing bracket with no opening bracket.

 #### The highlighted text: 

 > There are a few setup steps, which we'll cover below) but after that, you and your team are in control.

 #### The comment on the text: 
 _>replace this line with your comment<_

 ___
B.C. government DevHub URL: <https://mvp.developer.gov.bc.ca/docs/default/component/bc-developer-guide/content-partner-guide/#how-does-documentation-work-in-devhub> 
Markdown URL: <https://github.com/bcgov/bcdg/blob/main/docs/content-partner-guide.md>

**Comment by MonicaG** [comment]
Removed closing bracket in commit 2f6ee29555a476bc0665d0990cc14669dd7c64d5
